name: DockerAngular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 18.x
        uses: actions/setup-node@v1
        working-directory: ./angular
        with:
          node-version: '18.x'
      - name: Install dependencies
        working-directory: ./angular
        run: npm ci
      - name: Build
        working-directory: ./angular
        run: npm run build:ci
      - name: Test
        working-directory: ./angular
        run: npm run test:ci
      - name: Archive build
        if: success()
        working-directory: ./angular
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: angular/dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy_dist/angular
